### ISSUE TITLE
format request "the raven way"

### ISSUE THREAD

**Issue by fiws** [bendrucker/hapi-raven#17]
Just a suggestions:
I think Sentry displays a nicer UI if you format the request sent to sentry the right way (https://github.com/getsentry/raven-node/blob/master/lib/middleware/connect.js#L21)

maybe you can simply pass `request.raw.req` to `node-raven`, to get that data. 

The parser logic for it can be found here: https://github.com/getsentry/raven-node/blob/8c7303c2d1cdfe087042c80a3b74d638ca352445/lib/parsers.js#L66
## request right now

![image](https://cloud.githubusercontent.com/assets/3409958/18592004/42f852ba-7c35-11e6-893e-f26666c8f40f.png)
## in the right format

![image](https://cloud.githubusercontent.com/assets/3409958/18592066/82b9d70c-7c35-11e6-8ced-18de7d524bef.png)

**Comment by bendrucker** [comment]
Yeah I think you're right. Not sure about using the Raven parser for the `req`. Might need to be custom to get the right query stuff. Plus there's custom stuff like the request ID.

**Comment by fiws** [comment]
I think this is the defined format: https://docs.sentry.io/hosted/clientdev/interfaces/#special-interfaces

**Comment by bendrucker** [comment]
Good find!
