### ISSUE TITLE
Plugin name 'raven' does not match module name 'hapi-raven'

### ISSUE THREAD

**Issue by louisbl** [bendrucker/hapi-raven#2]
In the [hapi documentation](http://hapijs.com/api#plugins)
> Published plugins should use the same name as the name field in the 'package.json' file.

This is confusing and make it difficult to use this plugin with things like [Glue](https://github.com/hapijs/glue) or to declare dependency on it in another plugin.

**Comment by bendrucker** [comment]
Sure, please submit a PR
