### ISSUE TITLE
Server Plugin Reference

### ISSUE THREAD

**Issue by phoenixbox** [bendrucker/hapi-raven#23]
When trying to set User context,  I noticed my plugin was registered under the key name `hapi-raven` and not `raven`.

```
// Worked
server.plugins['hapi-raven'].client.setUserContext({ email: 'matt@example.com', id: '123'})
// Throws Undefined
server.plugins.raven.client.setUserContext({ email: 'matt@example.com', id: '123'})
```

Im registering my plugins like so

```
var plugins = [
  {
    register: require('hapi-raven'),
    options: {
      dsn: config.SENTRY_DSN
    }
  },
  ...otherPlugins
]

server.register(plugins, (err) => {
  if (err) {
    throw err;
  }
})
```

Is the named reference `server.plugins.raven` a mistake?

If so I can update the README docs and include some info about User context registration as that was my next step after raven setup. The next person might find that useful too.

Thanks for the plugin 🚀

**Comment by bendrucker** [comment]
You're correct. Docs PR would be appreciated.

**Comment by phoenixbox** [comment]
@bendrucker PR [here](https://github.com/bendrucker/hapi-raven/pull/24)

🚀

**Comment by bendrucker** [comment]
Changes merged
