### ISSUE TITLE
Include request.payload in exception payload

### ISSUE THREAD

**Issue by itsachen** [bendrucker/hapi-raven#26]
Hi!

Just a suggestion - I think it'd be really helpful to include `request.payload` in the [exception payload](https://github.com/bendrucker/hapi-raven/blob/master/index.js#L15). According to the [sentry HTTP interface](https://docs.sentry.io/clientdev/interfaces/http/) it should be fine to have it be the `data` value.

I'd be happy to put up a PR. What are your thoughts?

**Comment by bendrucker** [comment]
Doesn't sound right to me. Submitting bodies could get huge or reveal sensitive data. The docs point out:

> This data should not be provided by default as it can get quite large

If you can think of a good interface for selectively sending the body for certain errors I'd consider a PR for that.

**Comment by itsachen** [comment]
To be fair, sentry has [data scrubbing](https://docs.sentry.io/learn/sensitive-data/) enabled by default. I agree it's probably not best to send them by default, but hapi-raven should at least provide the ability to submit request payloads.

Do you mean [good](https://github.com/hapijs/good)? I'm between this package and a good-based solution (ex. good-sentry) for sentry reporting. Using good would enable users to customize (sanitize, truncate) payloads before handing them off to raven. However, I'm not sure if this is the direction you see this project going.

**Comment by bendrucker** [comment]
Not really thinking of good. Log pipelines are great but a lot of users prefer to pass real exceptions to Raven. Just something as simple as assigning some values on `request`, maybe `request.raven = {body: true}` and then reading that value from the error handler.

**Comment by DamodarSojka** [comment]
I agree that including the payload by default might not be the best idea, but it would be nice to be able to configure what is getting include. For example I have credentials object containing the userID included in almost all requests, that's a useful data to have on Sentry.

**Comment by bendrucker** [comment]
Sorry for leaving this open. I'll review a PR for adding more information from the request, perhaps via a generic function that takes the hapi request as an arg and returns an object. I don't really use Sentry for Node that much these days. I may make some time to port this and could have a look at the latest Sentry APIs and what extension points should exist at that point.
