### ISSUE TITLE
Thoughts on short circuiting when `options.dsn` isn't set

### ISSUE THREAD

**Issue by deedubs** [bendrucker/hapi-raven#31]
Currently `raven` is left to report that no DSN is specified and halting operation.  In cases where JSON logging output is being used this causes non-json to be logged.

```
raven@2.6.1 alert: no DSN provided, error reporting disabled
{"level":30,"time":1526591182856,"msg":"server started","pid":27,"hostname":"b71baed1b536","created":1526591182740,"started":1526591182850,"host":"b71baed1b536","port":80,"protocol":"http","id":"b71baed1b536:27:jhb0z3bo","uri":"http://b71baed1b536:80","address":"0.0.0.0","v":1}
```

Would you accept a PR that uses `server.log` in `hapi-raven` to stop if no options.dsn is set?

```
{"level":30,"time":1526591601296,"pid":42747,"hostname":"b71baed1b536","tags":["hapi-raven"],"data":"Unable to continue.  DNSnot provided","v":1}
{"level":30,"time":1526591182856,"msg":"server started","pid":27,"hostname":"b71baed1b536","created":1526591182740,"started":1526591182850,"host":"b71baed1b536","port":80,"protocol":"http","id":"b71baed1b536:27:jhb0z3bo","uri":"http://b71baed1b536:80","address":"0.0.0.0","v":1}
```

**Comment by bendrucker** [comment]
Hmm, maybe, I'd have to see the implementation. I don't love the idea of having to re-implement Raven's own behavior. I understand that it can be a pain to deal w/ ndjson that might sometimes have not-json in it. But that seems to me like a general problem—any library might occasionally print something to the console (e.g. a deprecation warning).

**Comment by bendrucker** [comment]
Revisiting this repo for another issue. Not planning on adding any silent noop feature outside of what Sentry already provides.
