### ISSUE TITLE
Upgrade to @sentry/node

### ISSUE THREAD

**Issue by mkg20001** [bendrucker/hapi-raven#34]
`raven` has been replaced by `@sentry/node`

**Comment by bendrucker** [comment]
Check out https://github.com/hydra-newmedia/hapi-sentry. Went to confirm that `hapi-sentry` was still available so I could rename this and found that package. I'll work with the maintainer to get it to a stable point (tests, complete docs, @1.0 release) and then go ahead and deprecate this repo/package.

**Comment by mkg20001** [comment]
Ok, thanks @bendrucker
